

# PERSONALIZATION
# Site variables
name: KTHAIS
# og: assets/img/og.png
logo: /assets/img/logo.png
original_repo: https://github.com/kthackais/kthais.com
description: KTHAIS community and events page
ga: UA-137575645-2
domain: kthais.com


# Style variables
accent_color: "#68a4cc"
events_overlay_color: "#000000"
background_color: "#FAFAFA"
footer_text_color: "#666666"

# START THEME 2
# accent_color: "#AA401B"
# events_overlay_color: "#225E50"
# END THEME 2

# START THEME 3
# accent_color: "#FF5722"
# events_overlay_color: "#2697FF"
# END THEME 3

# START THEME 4
# accent_color: "#FF5252"
# events_overlay_color: "#2697FF"
# END THEME 4

# START WINTER THEME
# accent_color: "#165E33" 
# events_overlay_color: "#AA504A"
# END WINTER THEME

# Author variables
author: KTHAIS
author-description: "KTHAIS wants to spread knowledge about the latest research within artificial intelligence and to contribute to an active AI-community, wherein students can increase their knowledge of the industry and find job opportunities, at KTH Royal Institute of Technology. We organise speeches and events with experts within the field, educational events, facilitate discussion, and provide resources to hasten their personal and professional development."
email: contact@kthais.com

# Social media + community variables
# twitter: kthais
fb: KTHAISociety
# fb-community: kthais
# slack: http://slack.kthais.com
# telegram: http://telegram.kthais.com

# instagram: kthais
github-org: kthackais



# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Stockholm
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:+0100
  TZOFFSETTO:+0200
  TZNAME:CEST
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=4SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:+0200
  TZOFFSETTO:+0100
  TZNAME:CET
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=4SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
